//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gadz.Tetris.Resources.Textos {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Jogo_pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Jogo_pt() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gadz.Tetris.Resources.Textos.Jogo-pt", typeof(Jogo_pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string Ajuda {
            get {
                return ResourceManager.GetString("Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose the style.
        /// </summary>
        public static string EscolheEstilo {
            get {
                return ResourceManager.GetString("EscolheEstilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Iniciar {
            get {
                return ResourceManager.GetString("Iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lines.
        /// </summary>
        public static string Linhas {
            get {
                return ResourceManager.GetString("Linhas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        public static string Nivel {
            get {
                return ResourceManager.GetString("Nivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tetris.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pausado.
        /// </summary>
        public static string Pausado {
            get {
                return ResourceManager.GetString("Pausado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Score.
        /// </summary>
        public static string Pontuacao {
            get {
                return ResourceManager.GetString("Pontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressione ENTER para continuar.
        /// </summary>
        public static string PressioneEnterParaContinuar {
            get {
                return ResourceManager.GetString("PressioneEnterParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pressione qualquer tecla para continuar.
        /// </summary>
        public static string PressioneParaContinuar {
            get {
                return ResourceManager.GetString("PressioneParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string Proximo {
            get {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound Off.
        /// </summary>
        public static string SomDesligado {
            get {
                return ResourceManager.GetString("SomDesligado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound On.
        /// </summary>
        public static string SomLigado {
            get {
                return ResourceManager.GetString("SomLigado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tetris.
        /// </summary>
        public static string TaxaTetris {
            get {
                return ResourceManager.GetString("TaxaTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        public static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press SHIFT to turn the sound on or off.
        /// </summary>
        public static string ToggleSoundKey {
            get {
                return ResourceManager.GetString("ToggleSoundKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Speed.
        /// </summary>
        public static string Velocidade {
            get {
                return ResourceManager.GetString("Velocidade", resourceCulture);
            }
        }
    }
}
